import type { SkillGroup } from "@/types/content";

export const skillGroups: SkillGroup[] = [
  {
    name: "Languages",
    description: "Foundations for product, systems, data and algorithmic work.",
    skills: ["Python", "Java", "C", "JavaScript", "TypeScript", "SQL", "R"],
  },
  {
    name: "Computer Science",
    description: "Core concepts that shape how I reason about software.",
    skills: [
      "Data Structures & Algorithms",
      "Object-Oriented Programming",
      "Operating Systems",
      "DBMS",
      "Computer Networks",
      "Linear Algebra",
      "Discrete Mathematics",
      "Probability",
      "Statistical Modelling",
      "Computational Statistics",
    ],
  },
  {
    name: "Web Engineering",
    description: "Interface and service layers for complete web products.",
    skills: [
      "HTML",
      "CSS",
      "React",
      "Next.js",
      "Tailwind CSS",
      "React Native",
      "Expo",
      "Expo Router",
      "Flask",
      "Node.js",
      "Express.js",
      "REST APIs",
      "API Integration",
    ],
  },
  {
    name: "Data & AI",
    description: "Applied ML, language systems, vision and explainability.",
    skills: [
      "Machine Learning",
      "Deep Learning",
      "Natural Language Processing",
      "Computer Vision",
      "Transformers",
      "Vision Transformers",
      "Sentence Transformers",
      "Text Embeddings",
      "TF-IDF",
      "Semantic Similarity",
      "Cosine Similarity",
      "K-Means Clustering",
      "K-Nearest Neighbors",
      "Random Forest",
      "Recommendation Systems",
      "Explainable AI",
      "Uncertainty Estimation",
      "Graph Neural Networks",
      "3D Image Segmentation",
    ],
  },
  {
    name: "Generative AI",
    description: "Areas of technical work and active exploration.",
    skills: [
      "Generative AI",
      "LLM Applications",
      "RAG",
      "Embeddings",
      "AI Agents",
      "Agentic Workflows",
      "Prompt Engineering",
      "OpenRouter",
      "Knowledge-base AI Systems",
    ],
  },
  {
    name: "Cloud & DevOps",
    description: "Infrastructure patterns for repeatable software delivery.",
    skills: [
      "AWS",
      "Docker",
      "Kubernetes",
      "Jenkins",
      "CI/CD",
      "Linux",
      "Containerization",
      "Dockerfiles",
      "Kubernetes Pods",
      "Kubernetes Deployments",
      "Kubernetes Services",
      "Kubernetes Namespaces",
    ],
  },
  {
    name: "Databases",
    description: "Relational and document data modelling.",
    skills: ["MySQL", "PostgreSQL", "MongoDB", "SQL", "Relational Concepts", "CRUD"],
  },
  {
    name: "Security",
    description: "A supporting engineering discipline, not the portfolio identity.",
    skills: [
      "Cybersecurity Fundamentals",
      "CTF",
      "Bug Bounty",
      "Linux Security Fundamentals",
      "Web & Application Security",
    ],
  },
];

export const toolGroups = [
  { label: "Web", tools: ["React", "Next.js", "Node.js", "Express.js", "Flask", "Tailwind"] },
  {
    label: "AI / Data",
    tools: ["NumPy", "Pandas", "Scikit-learn", "Sentence Transformers", "Power BI"],
  },
  { label: "Cloud / DevOps", tools: ["AWS", "Docker", "Kubernetes", "Jenkins", "Linux"] },
  { label: "Development", tools: ["Git", "GitHub", "StarUML", "Selenium"] },
] as const;
